/**
 * Domain types for the Book Tracker.
 *
 * This file is the contract between the UI, the storage layer, and the
 * future backend. Change types here only via a spec amendment — every
 * consumer will follow.
 */

export type ReadingStatus = "want" | "reading" | "read";

/**
 * A book in the user's library.
 *
 * `id` and `createdAt` are assigned by the storage layer; callers that
 * create a book supply everything else via {@link BookInput}.
 */
export interface Book {
  /** UUID v4, generated by the storage layer. */
  id: string;
  /** 1–200 characters, trimmed. */
  title: string;
  /** 1–120 characters, trimmed. */
  author: string;
  status: ReadingStatus;
  /** Optional `http(s)://` URL. */
  coverUrl?: string;
  /**
   * Tags are normalized at the validator: lowercased, trimmed, deduplicated,
   * capped at 10 entries, each entry ≤ 24 characters.
   */
  tags: string[];
  /** ISO 8601 timestamp, set by the storage layer on creation. */
  createdAt: string;
}

/** What the UI submits to add a book. `id` and `createdAt` are storage-side. */
export type BookInput = Omit<Book, "id" | "createdAt">;
