/**
 * Domain types for the Book Tracker.
 *
 * This file is the contract between the UI, the storage layer, and the
 * future backend. Change types here only via a spec amendment — every
 * consumer will follow.
 */

import type { Quote } from "./quote";
import type { Review } from "./review";

export type ReadingStatus = "want" | "reading" | "read";

/**
 * A book in the user's library.
 *
 * `id` and `createdAt` are assigned by the storage layer; callers that
 * create a book supply everything else via {@link BookInput}.
 */
export interface Book {
  /** UUID v4, generated by the storage layer. */
  id: string;
  /** 1–200 characters, trimmed. */
  title: string;
  /** 1–120 characters, trimmed. */
  author: string;
  status: ReadingStatus;
  /** Optional `http(s)://` URL. */
  coverUrl?: string;
  /**
   * Tags are normalized at the validator: lowercased, trimmed, deduplicated,
   * capped at 10 entries, each entry ≤ 24 characters.
   */
  tags: string[];
  /** ISO 8601 timestamp, set by the storage layer on creation. */
  createdAt: string;
  /**
   * Optional 1-5 rating. Absent means "not rated"
   * (spec 006 D2). Integers only — no half-stars, no 0
   * (spec 006 D1). Set by the user via the detail page
   * or the BookForm.
   */
  rating?: 1 | 2 | 3 | 4 | 5;
  /**
   * Optional review of the book. Discriminated union: plain text
   * or rich-text (ProseMirror JSON). Legacy plain strings are
   * normalised to { format: "plain", body } at the validator
   * boundary (spec 008 D2, D6).
   */
  review?: Review | string;
  /**
   * Optional quotes from the book. Each quote is a passage
   * with optional page number and optional personal note
   * (spec 009 §7.1). Embedded in the Book record — no
   * separate aggregate, no extra storage methods. Capped
   * at 200 entries per book by `validateBookInput`.
   */
  quotes?: Quote[];
  /**
   * Optional date the user started reading this book. ISO
   * 8601 calendar date in `YYYY-MM-DD` form (NOT a datetime
   * — spec 012 D2). Independent of `status`: a book with
   * status 'want' may have a `startedAt`, and a book with
   * status 'read' may have neither. Validated by
   * `validateBookInput` (spec 012 D1, D3, D4).
   */
  startedAt?: string;
  /**
   * Optional date the user finished reading. Same shape
   * and rules as `startedAt`. Cross-field rule: if both
   * are set, `startedAt <= finishedAt` (spec 012 D4).
   */
  finishedAt?: string;
}

/**
 * What the UI submits to add or update a book. `id` and `createdAt` on the
 * book itself are storage-side; nested `Quote` items are full Quotes
 * (the UI generates `id` and `createdAt` for new quotes in
 * `BookDetail.handleSaveQuote`, spec 009 T6).
 *
 * The {@link QuoteInput} type is used only at the dialog boundary — the
 * form payload the user types in is id-less; the upgrade to a full
 * {@link Quote} happens before `updateBook` is called.
 */
export type BookInput = Omit<Book, "id" | "createdAt">;
