/**
 * Domain types for the Book Tracker.
 *
 * This file is the contract between the UI, the storage layer, and the
 * future backend. Change types here only via a spec amendment — every
 * consumer will follow.
 */

export type ReadingStatus = "want" | "reading" | "read";

/**
 * A book in the user's library.
 *
 * `id` and `createdAt` are assigned by the storage layer; callers that
 * create a book supply everything else via {@link BookInput}.
 */
export interface Book {
  /** UUID v4, generated by the storage layer. */
  id: string;
  /** 1–200 characters, trimmed. */
  title: string;
  /** 1–120 characters, trimmed. */
  author: string;
  status: ReadingStatus;
  /** Optional `http(s)://` URL. */
  coverUrl?: string;
  /**
   * Tags are normalized at the validator: lowercased, trimmed, deduplicated,
   * capped at 10 entries, each entry ≤ 24 characters.
   */
  tags: string[];
  /** ISO 8601 timestamp, set by the storage layer on creation. */
  createdAt: string;
  /**
   * Optional 1-5 rating. Absent means "not rated"
   * (spec 006 D2). Integers only — no half-stars, no 0
   * (spec 006 D1). Set by the user via the detail page
   * or the BookForm.
   */
  rating?: 1 | 2 | 3 | 4 | 5;
  /**
   * Optional free-form review. Plain text, max 10 000
   * characters after trim. Absent means "no review"
   * (spec 007 D3). Will be upgraded to a structured
   * rich-text state in a future spec (D9).
   */
  review?: string;
}

/** What the UI submits to add a book. `id` and `createdAt` are storage-side. */
export type BookInput = Omit<Book, "id" | "createdAt">;
