/**
 * Domain types for a single quote attached to a book.
 *
 * A quote is the passage of text the reader wants to remember, with
 * optional attribution (page number) and an optional personal note.
 * Quotes are stored embedded in {@link Book.quotes} (spec 009 D2) — no
 * separate aggregate, no extra storage methods.
 *
 * Rich text inside `text` or `note` is explicitly out of scope; both are
 * plain strings, same posture as `Book.review` (spec 007). When spec 008
 * upgrades the review to a rich-text state, it should also upgrade these
 * two fields in the same way.
 */
export interface Quote {
  /** UUID v4, generated by the storage layer on creation. */
  id: string;
  /** 1–2000 characters after trim. Required. */
  text: string;
  /** Optional page number: integer 1..99999. */
  page?: number;
  /** Optional personal note: 1–1000 characters after trim. */
  note?: string;
  /** ISO 8601 timestamp, set by the storage layer on creation. */
  createdAt: string;
}

/** What the UI submits to add or edit a quote. `id` and `createdAt` are storage-side. */
export type QuoteInput = Omit<Quote, "id" | "createdAt">;
